# Generated by Django 4.2.1 on 2023-06-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
