# Generated by Django 4.2.1 on 2023-06-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orders_selledproduct_delete_checkout_orders_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.DeleteModel(
            name='SelledProduct',
        ),
    ]
