# Generated by Django 4.2.1 on 2023-06-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
