# Generated by Django 4.2.1 on 2023-06-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
